const emptySeat=[
    [
      null,
      { id: 1, number: "A1"},
      { id: 2, number: "A2"},
      { id: 3, number: "A3"},
      { id: 4, number: "A4"},
      { id: 5, number: "A5"},
      null,
      { id: 6, number: "A6"},
      { id: 7, number: "A7"},
      { id: 8, number: "A8"},
      { id: 9, number: "A9"},
      { id: 10, number: "A10"},
      null
    ],
    [
      { id: 13, number: "B1"},
      { id: 14, number: "B2"},
      { id: 15, number: "B3"},
      { id: 16, number: "B4"},
      { id: 17, number: "B5"},
      { id: 18, number: "B6"},
      null,
      { id: 19, number: "B7"},
      { id: 20, number: "B8"},
      { id: 21, number: "B9"},
      { id: 22, number: "B10"},
      { id: 23, number: "B11"},
      { id: 24, number: "B12"}
    ],
    [
      { id: 26, number: "C2" },
      { id: 25, number: "C1" },
      { id: 27, number: "C3" },
      { id: 28, number: "C4" },
      { id: 29, number: "C5" },
      { id: 30, number: "C6" },
      null,
      { id: 32, number: "C8" },
      { id: 31, number: "C7" },
      { id: 33, number: "C9" },
      { id: 34, number: "C10" },
      { id: 35, number: "C11" },
      { id: 36, number: "C12" }
    ],
    [
      { id: 37, number: "D1" },
      { id: 38, number: "D2" },
      { id: 39, number: "D3" },
      { id: 40, number: "D4" },
      { id: 41, number: "D5" },
      { id: 42, number: "D6" },
      null,
      { id: 43, number: "D7" },
      { id: 44, number: "D8" },
      { id: 45, number: "D9" },
      { id: 46, number: "D10" },
      { id: 47, number: "D11" },
      { id: 48, number: "D12" },
    ],
    [
      { id: 49, number: "E1" },
      { id: 50, number: "E2" },
      { id: 51, number: "E3" },
      { id: 52, number: "E4" },
      { id: 53, number: "E5" },
      { id: 54, number: "E6" },
      null,
      { id: 55, number: "E7" },
      { id: 56, number: "E8" },
      { id: 57, number: "E9" },
      { id: 58, number: "E10" },
      { id: 59, number: "E11" },
      { id: 60, number: "E12" },
    ],
    [
      { id: 61, number: "F1" },
      { id: 62, number: "F2" },
      { id: 63, number: "F3" },
      { id: 64, number: "F4" },
      { id: 65, number: "F5" },
      { id: 66, number: "F6" },
      null,
      { id: 67, number: "F7" },
      { id: 68, number: "F8" },
      { id: 69, number: "F9" },
      { id: 70, number: "F10" },
      { id: 71, number: "F11" },
      { id: 72, number: "F12" },
    ],
    [
      { id: 73, number: "G1" },
      { id: 74, number: "G2" },
      { id: 75, number: "G3" },
      { id: 76, number: "G4" },
      { id: 77, number: "G5" },
      { id: 78, number: "G6" },
      null,
      { id: 79, number: "G7" },
      { id: 80, number: "G8" },
      { id: 81, number: "G9" },
      { id: 82, number: "G10" },
      null,
      null
    ]
  ];

  export default emptySeat;